[programs.localnet]
anchor_play_3 = "BPvPwaQK28fsMHNJLf4i9jcsaA258tXGzrEaNQWRVJE5"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/ilmoi/.config/solana/id.json"

[scripts]
test = "ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
